name: Greeting from Customize Action
on: push
jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -lart ./.github/actions/toolkit                     
      - uses: ./.github/actions/toolkit
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"